### ISSUE TITLE
Wrong conversion from string to short string felt for simple numbers

### ISSUE THREAD

**Issue by ccarnino** [sekai-studio/starknet-libs#2]
Hello team. 
I have been working on a web UI that uses your library https://cairo-utils-web.vercel.app ([repo](https://github.com/ccarnino/cairo-utils-web)).

During the use I can see that the library works as intended for a string like "ciao" -> 1667850607. But it returns a wrong result when the input is a simple number "1" -> 49, instead of "1" (both decimal and hex outputs are wrong).

I compared the output with something created by another person at https://util.turbofish.co/

Are you aware of this issue?
Thanks

**Comment by jag-lotus** [comment]
Hi @ccarnino,

"1" returns 49 because it is the decimal representation of the character "1" in ASCII/utf-8 as this lib only works with strings.

For example if you store the string "ab12" it will return 0x61623132 or `97 * 256^3 + 98 * 256^2 + 49 * 256^1 + 50 * 256^0 =  1633825074`. Hence "1" will be stored as an ASCII/utf-8 character with the value of 0x31 or 49

I hope this was clear enough. We are working on a major upgrade and will write a proper documentation this time.
